### ISSUE TITLE
Need to more clarification

### ISSUE THREAD

**Issue by ghost** [app-generator/sample-django-file-manager#1]
Hello @app-generator ,

Could you please explain it more?

**Comment by app-generator** [comment]
Hello @mominur-helios 

The UI needs to provide a visual way to manage a directory structure. 
In our case, is the `MEDIA` directory

The view needs to provide two panels:

- Left panel: for directories 
- right panel: files of the selected directory 

A similar product is Windows Explorer, where the users can select a directory from the left panel and interact with the files of that directory on the right panel 

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/eadcfd2d-c9a7-4fba-91f7-712a4e41cb2f)


A quick solution might be to pull the Directory Tree as JSON from the backend and use it to populate the views. 

Regarding the actions, the users can

- create / rename / update DIRS (on left)
- upload, delete and view files on the right 

Let me know if you need more input. 

TY!

**Comment by ghost** [comment]
Got it. That means I need to create necessary models, views, templates and so on, right? @app-generator

**Comment by app-generator** [comment]
The source of information is the MEDIA directory, no models are required. 

As mentioned in the README, please take into account the routing:

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/01e49059-7b87-4ff1-8430-0569e369c591)

An important aspect is this:

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/675c54fd-2b77-410b-b220-0e79ea6d6c5f)

Let me know if you need more input.

TY!

**Comment by app-generator** [comment]
Closing.
