### ISSUE TITLE
Files View Option - Needs to be popup

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-file-manager#10]
Hello @mominur-helios 

The view option works but needs to be a modal popup, centered that uses a decent viewport, let's say 60% screen width. 

The current solution that redirect the user to another page is not optimal. 

Please take a look.
TY!

**Comment by ghost** [comment]
In the current solution modal popup is work only for images and videos. You want modal popup will works for every files? @app-generator

**Comment by app-generator** [comment]
Yes @mominur-helios 

- PDF -> should be ok
- TXT -> should be OK
- IMAGES (png. jpg) 
- CSV -> text handler 

These are the common handlers we should support in this first version of the tool. 

Ty!

**Comment by app-generator** [comment]
Validated. CLosing.
