### ISSUE TITLE
2nd Level Directories - Files not listed

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-file-manager#13]
Hello @mominur-helios 

Please pull the latest changes. I just added sample files to highlight the issue. 
TY!

---

I'm accessing `dir1`, a 2nd level DIR:

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/5cdf634a-ae07-491b-acb7-942b5fbb629e)

---

Here is the UI & the related issues:

- URI not clean: `http://localhost:8000/file-manager/project1%255Cdir1/`
  - Sequence `%255C` is still there
- Breadcrumb not clean
  - `/file-manager/project1%5Cdir1/` 
- DIR contents show no files but we have a TXT file inside:
 
![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/e6c57d50-9cf9-4f2a-83b1-3962e22d99e6)

--- 
 
> Full DIR Tree

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/5d0191d5-cc82-4db9-a7d3-f174f66bdf6f)

**Comment by ghost** [comment]
Let me check again, sorry for the inconvenience. It's working fine in here. I can't get any issue while testing that's why the issues are still there. @app-generator 

https://github.com/app-generator/sample-django-file-manager/assets/101915710/3102f5fa-6b20-4fa6-88bf-156d4126b958

**Comment by app-generator** [comment]
I just checked the code. Seems Ok
I suspect the code is not cross-platform.

If possible, please do a test in Windows, PY3.

For sure, the issue will bump.

Ty!

**Comment by app-generator** [comment]
Validated. Closing.
