### ISSUE TITLE
Added BreadCrumbs on top of the widget

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-file-manager#6]
Hello @mominur-helios 

Please add the breadcrumbs that suggest the current directory path above the widget

`ROOT (media) / dir1 / dir2`

In the above `breadcrumb`,  **dir2** is the current on (not click-able) but `dir1` needs to be click-able to allow the user to get back

In the current version, if the user navigates in the tree, cannot go back.

Please take a look. 
TY!

**Comment by ghost** [comment]
Hello @app-generator ,

I have fixed all the issues but the design still not looks good. If you give me a design prototype then it will be better.

**Comment by app-generator** [comment]
Hello @mominur-helios 

Let's focus right now on the functional part with a super minimal UI. 

At this stage, my advice is to follow 100% the initial kickOff:

https://github.com/app-generator/sample-django-file-manager/issues/1#issuecomment-1605958381

This sentence is particularly important:

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/c3098798-f005-48a6-8f35-22728567e27c)

Once the functional code is stable, we can iterate on the design. 

TY!

**Comment by app-generator** [comment]
Hello @mominur-helios 

The left panel needs some improvements:

- The file separator needs to be always `/`
- replace `file-manager` label with ROOT
- the segment `project1 / dir1` needs to be:
  -  `project1` -> click-able (being a parent directory)
  -  `dir1` -> not click-able (being the current one)

Also, all the directories need to start expanded

Please take a look. TY!

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/977571bb-00be-40e9-a33b-74162f725820)

**Comment by app-generator** [comment]
Validated. Closing.
