### ISSUE TITLE
Right Panel Improvements

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-file-manager#8]
Hello @mominur-helios 

The **RIGHT** panel now shows the files as cards. This is good but might be a problem when we have many files. 

Please apply the following changes:

- use a table (not paginated) with rows:
- file name
- file type (PDF, TXT, CSV, JPG)
  - basically, the extension of the file uppercased 
- controls:
  - View (via a modal popup) - we should support all types 
  - Download
  - Delete (with confirmation)

Please take a look. Ty!

**Comment by ghost** [comment]
Left panel or Right?
It seems you are talking about right panel @app-generator

**Comment by app-generator** [comment]
**RIGHT** ... @mominur-helios 
Ty for the correction :)

**Comment by app-generator** [comment]
Hello @mominur-helios 

The Right Panel required updates:

- The DIR Tree needs to be always expanded
- On DIR click, the page needs to be reloaded for the current DIR
  - For instance, we have `project1 / dir1` and the user can't ever see the contents of `project1` 

Also, the breadCrumbs need a small layout improvement. Needs to be:

`MEDIA / project1 / dir1` where

- `MEDIA` is a hardcoded name (not click-able)
- `project1` being the parent, is click-able 
- `dir1`, being the current one is NOT click-able

Please notice the `space` between segments: 

**MEDIA**`SPACE`**/**`SPACE`**project1**`SPACE`**/**`SPACE`**dir1**

Please take a look. 
TY!

**Comment by ghost** [comment]
`The DIR Tree needs to be always expanded` you mean the files will be expanded too? Currently the folder inside a directory is expanded. @app-generator 

![Screenshot from 2023-07-04 11-55-33](https://github.com/app-generator/sample-django-file-manager/assets/101915710/6de44628-92fc-46f7-bb22-f325317a1120)

**Comment by app-generator** [comment]
Hello @mominur-helios 

The initial state is this:

- RIGHT panel: all directories expanded (files not visible on the RIGHT)
- LEFT: FIles in the current DIR (if any)

using the files & DIRs currently saved in the REPO, the layout is correct:

![image](https://github.com/app-generator/sample-django-file-manager/assets/51070104/d476f8a9-d60e-4fc8-a370-2e8fad5f9680)

The problem occurs when the user clicks on `project1` and the DIR collapses, instead of reloading the page with the contents of `project1`

Currently, the only way for the user to list the contents of `project1`, he needs to access the URL directly:

http://localhost:8000/file-manager/project1/

Please take a look. 
TY!

**Comment by ghost** [comment]
You want that, the DIR won't be collapse and the contents will shows? @app-generator

**Comment by app-generator** [comment]
Validated. Closing.
